package com.back.revi.reviback.chauffage.model;

public enum ChauffegeType {
	ELECTRIQUE_CHAUDIERE,
	ELECTRIQUE_PLAFOND_PLANCHER,
	ELECTRIQUE_RADIATEUR,
	GAZ_CHAUDIERE_CONDENSATION,
	GAZ_CHAUDIERE,
	GAZ_RADIATEUR,
	GAZ_POELE,
	BOIS_CHAUDIERE,
	BOIS_CHEMINEE,
	BOIS_POELE,
	POMPE_CHALEUR_SOL_EAU,
	POMPE_CHALEUR_SOL_AIR,
	POMPE_CHALEUR_AIR_AIR,
	POMPE_CHALEUR_AIR_EAU,
	POMPE_CHALEUR_EAU_EAU,
	SOLAIRE_SSC,
	SOLAIRE_PLANCHER,
	SOLAIRE_AEROVOLTAIQUES,
	SOLAIRE_PHOTOVOLTAIQUES
}
