package com.back.revi.reviback.isolation.model;

public enum IsolationType {
	COMBLE_PERDUES,
	COMBLE_AMENAGES,
	MURS_INTERIEUR,
	MURS_EXTERIEUR,
	SOL_LOCAL_CHAUFFE,
	SOL_TERRE_PLEIN,
	SOL_VIDE_SANITAIRE,
	SOL_PLANCHER_ETAGE,
	FENETRES_SUR_PLACE,
	FENETRES_REFECTION
}
